name: SLA Monitor

on:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  check-sla:
    runs-on: ubuntu-latest
    steps:
      - name: Check for SLA Violations
        uses: actions/github-script@v6
        with:
          script: |
            const SLAs = {
              bug: 3,       // days
              enhancement: 7,
              'technical debt': 10
            }

            const issues = await github.paginate(
              github.rest.issues.listForRepo,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open'
              }
            )

            for (const issue of issues) {
              if (issue.pull_request) continue;
              const created = new Date(issue.created_at)
              const now = new Date()
              const diffDays = (now - created) / (1000 * 60 * 60 * 24)

              for (const label of issue.labels) {
                const labelName = label.name
                const sla = SLAs[labelName]
                if (sla && diffDays > sla) {
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    body: 'SLA Violation: This issue is open for more than ${sla} days. Please review.'
                  })
                }
              }
            }
